//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rachetZPNazarova
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointStaff
    {
        public int IDPoint { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idTypePoint { get; set; }
        public Nullable<double> SummaPoint { get; set; }
        public Nullable<int> idUserSystem { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual TypePoint TypePoint { get; set; }
        public virtual UserSystem UserSystem { get; set; }
    }
}
